/vis/open OGL 600x600-0+0

/vis/drawVolume

#/vis/viewer/set/viewpointThetaPhi 30 50
/vis/viewer/zoom 0.8

/vis/viewer/set/style wireframe
#/vis/viewer/set/background 0.9 0.9 0.9
#/vis/viewer/set/defaultColour black
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 20

/vis/geometry/set/visibility world 0 false

/vis/viewer/set/autoRefresh true
/vis/verbose warnings

#/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.


/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
/vis/scene/endOfEventAction accumulate
#/vis/modeling/trajectories/drawByCharge-0/default/setLineWidth 2
